# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'ubuntu-lucid-64'
  config.vm.box_url = 'http://files.vagrantup.com/lucid64.box'
  config.vm.forward_port 25565, 25565

  config.vm.provision :chef_solo do |chef|
    config.vm.share_folder "scratch", "/tmp/scratch", "scratch"
    chef.cookbooks_path = "../../cookbooks"
    chef.roles_path = "../../roles"
    chef.data_bags_path = "../../data_bags"
    chef.add_role "ec2-minecraft-server"
=begin
    chef.json.merge!(
                     :minecraft => {
                       :message => 'FruityCraft Minecraft Server!',
                       :ops => [
                                'philloop',
                                'insane_creepah',
                                'stooferus'
                               ],
                       :whitelist => [
                                      'stooferus',
                                      'philloop',
                                      'insane_creepah',
                                      'Tobsy4inc',
                                      'Ties100100',
                                      'jamibo12'
                                    ],
                       :users => {
                         'stooferus' => { 'groups' => ['Owner']},
                         'insane_creepah' => { 'groups' => ['Admin']},
                         'philloop' => { 'groups' => ['Admin']}
                       }
                     })
=end
  end
end
