# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-lucid-64"
  config.vm.forward_port 25565, 25565

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../cookbooks"
    chef.roles_path = "../../roles"
    chef.data_bags_path = "../../data_bags"
    chef.add_role "minecraft-server"
  end
end
